#Spun off from print_reports so that the file doesn't get too bad, holds some of the bigger listings of CLI options
#See what imports I might need to bring in here for this to work

def print_platforms():
    #Lists all of the platform options available to us
    print("Here are all the platforms that there are!")
    print("3. Linux")
    print("4. Nintendo 64")
    print("5. Wii")
    print("6. PC (Microsoft Windows)")
    print("7. PlayStation")
    print("8. PlayStation 2")
    print("9. PlayStation 3")
    print("11. Xbox")
    print("12. Xbox 360")
    print("13. DOS")
    print("14. Mac")
    print("15. Commodore C64/128/MAX")
    print("16. Amiga")
    print("18. Nintendo Entertainment System")
    print("19. Super Nintendo Entertainment System")
    print("20. Nintendo DS")
    print("21. Nintendo GameCube")
    print("22. Game Boy Color")
    print("23. Dreamcast")
    print("24. Game Boy Advance")
    print("25. Amstrad CPC")
    print("26. ZX Spectrum")
    print("27. MSX")
    print("29. Sega Mega Drive/Genesis")
    print("30. Sega 32X")
    print("32. Sega Saturn")
    print("33. Game Boy")
    print("34. Android")
    print("35. Sega Game Gear")
    print("36. Xbox Live Arcade")
    print("37. Nintendo 3DS")
    print("38. PlayStation Portable")
    print("39. iOS")
    print("41. Wii U")
    print("42. N-Gage")
    print("44. Tapwave Zodiac")
    print("45. PlayStation Network")
    print("46. PlayStation Vita")
    print("47. Virtual Console")
    print("48. PlayStation 4")
    print("49. Xbox One")
    print("50. 3DO Interactive Multiplayer")
    print("51. Family Computer Disk System")
    print("52. Arcade")
    print("53. MSX2")
    print("55. Legacy Mobile Device")
    # print("56. WiiWare") #Removed?
    print("57. WonderSwan")
    print("58. Super Famicom")
    print("59. Atari 2600")
    print("60. Atari 7800")
    print("61. Atari Lynx")
    print("62. Atari Jaguar")
    print("63. Atari ST/STE")
    print("64. Sega Master System/Mark III")
    print("65. Atari 8-bit")
    print("66. Atari 5200")
    print("67. Intellivision")
    print("68. ColecoVision")
    print("69. BBC Microcomputer System")
    print("70. Vectrex")
    print("71. Commodore VIC-20")
    print("72. Ouya")
    print("73. BlackBerry OS")
    print("74. Windows Phone")
    print("75. Apple II")
    print("77. Sharp X1")
    print("78. Sega CD")
    print("79. Neo Geo MVS")
    print("80. Neo Geo AES")
    print("82. Web browser")
    print("84. SG-1000")
    print("85. Donner Model 30")
    print("86. TurboGrafx-16/PC Engine")
    print("87. Virtual Boy")
    print("88. Odyssey")
    print("89. Microvision")
    print("90. Commodore PET")
    print("91. Bally Astrocade")
    #print("92. SteamOS") #Removed?
    print("93. Commodore 16")
    print("94. Commodore Plus/4")
    print("95. PDP-1")
    print("96. PDP-10")
    print("97. PDP-8")
    print("98. DEC GT40")
    print("99. Family Computer")
    print("100. Analogue electronics")
    print("101. Ferranti Nimrod Computer")
    print("102. EDSAC")
    print("103. PDP-7")
    print("104. HP 2100")
    print("105. HP 3000")
    print("106. HP SDS Sigma 7")
    print("107. Call-A-Computer time-shared mainframe computer system")
    print("108. PDP-11")
    print("109. CDC Cyber 70")
    print("110. PLATO")
    print("111. Imlac PDS-1")
    print("112. Microcomputer")
    print("113. OnLive Game System")
    print("114. Amiga CD32")
    print("115. Apple IIGS")
    print("116. Acorn Archimedes")
    print("117. Philips CD-i")
    print("118. FM Towns")
    print("119. Neo Geo Pocket")
    print("120. Neo Geo Pocket Color")
    print("121. Sharp X68000")
    print("122. Nuon")
    print("123. WonderSwan Color")
    print("124. SwanCrystal")
    print("125. PC-8800 Series")
    print("126. TRS-80")
    print("127. Fairchild Channel F")
    print("128. PC Engine SuperGrafx")
    print("129. Texas Instruments TI-99")
    print("130. Nintendo Switch")
    print("131. Nintendo PlayStation")
    print("132. Amazon Fire TV")
    print("133. Odyssey 2 / Videopac G7000")
    print("134. Acorn Electron")
    print("135. Hyper Neo Geo 64")
    print("136. Neo Geo CD")
    print("137. New Nintendo 3DS")
    print("138. VC 4000")
    print("139. 1292 Advanced Programmable Video System")
    print("140. AY-3-8500")
    print("141. AY-3-8610")
    print("142. PC-50X Family")
    print("143. AY-3-8760")
    print("144. AY-3-8710")
    print("145. AY-3-8603")
    print("146. AY-3-8605")
    print("147. AY-3-8606")
    print("148. AY-3-8607")
    print("149. PC-9800 Series")
    print("150. Turbografx-16/PC Engine CD")
    print("151. TRS-80 Color Computer")
    print("152. FM-7")
    print("153. Dragon 32/64")
    print("154. Amstrad PCW")
    print("155. Tatung Einstein")
    print("156. Thomson MO5")
    print("157. NEC PC-6000 Series")
    print("158. Commodore CDTV")
    print("159. Nintendo DSi")
    # print("160. Nintendo eShop") #Removed?
    print("161. Windows Mixed Reality")
    print("162. Oculus VR")
    print("163. SteamVR")
    print("164. Daydream")
    print("165. PlayStation VR")
    print("166. Pokémon mini")
    print("167. PlayStation 5")
    print("169. Xbox Series X|S")
    print("170. Google Stadia")
    print("238. DVD Player")
    print("240. Zeebo")
    print("274. PC-FX")
    print("306. Satellaview")
    print("307. Game & Watch")
    print("308. Playdia")
    print("309. Evercade")
    print("339. Sega Pico")
    print("372. OOParts")
    print("374. Sharp MZ-2200")
    print("375. Epoch Cassette Vision")
    print("376. Epoch Super Cassette Vision")
    print("377. Plug & Play")
    print("378. Gamate")
    print("379. Game.com")
    print("380. Casio Loopy")
    print("381. Playdate")
    print("382. Intellivision Amico")
    print("384. Oculus Quest")
    print("385. Oculus Rift")
    print("386. Meta Quest 2")
    print("390. PlayStation VR2")
    print("405. Windows Mobile")
    print("407. HyperScan")
    print("410. Atari Jaguar CD")
    print("411. Handheld Electronic LCD")
    print("412. Leapster")
    print("413. Leapster Explorer/LeadPad Explorer")
    print("414. LeapTV")
    print("416. Nintendo 64DD")
    print("417. Palm OS")
    print("439. V.Smile")
    print("440. Visual Memory Unit / Visual Memory System")
    print("441. PocketStation")
    print("471. Meta Quest 3")
    print("474. Gizmondo")
    print("476. Apple Pippin")
    print("477. Panasonic Jungle")
    print("478. Panasonic M2")
    print("486. Digiblast")
    #any others needed?
    print()

def print_genres():
    #Lists all of the genre options available to us
    print("Here are all the genres that there are!")
    print("2. Point-and-click")
    print("4. Fighting")
    print("5. Shooter")
    print("7. Music")
    print("8. Platform")
    print("9. Puzzle")
    print("10. Racing")
    print("11. Real Time Strategy (RTS)")
    print("12. Role-playing (RPG)")
    print("13. Simulator")
    print("14. Sport")
    print("15. Strategy")
    print("16. Turn-based strategy (TBS)")
    print("24. Tactical")
    print("25. Hack and slash/Beat \'em up")
    print("26. Quiz/Trivia")
    print("30. Pinball")
    print("31. Adventure")
    print("32. Indie")
    print("33. Arcade")
    print("34. Visual Novel")
    print("35. Card & Board Game")
    print("36. MOBA")
    # any others needed?
    print()

def print_themes():
    #Lists all of the theme options available to us
    print("Here are all the themes that there are!")
    print("1. Action")
    print("17. Fantasy")
    print("18. Science fiction")
    print("19. Horror")
    print("20. Thriller")
    print("21. Survival")
    print("22. Historical")
    print("23. Stealth")
    print("27. Comedy")
    print("28. Business")
    print("31. Drama")
    print("32. Non-fiction")
    print("33. Sandbox")
    print("34. Educational")
    print("35. Kids")
    print("38. Open world")
    print("39. Warfare")
    print("40. Party")
    print("41. 4X (explore, expand, exploit, and exterminate)")
    print("42. Erotic")
    print("43. Mystery")
    print("44. Romance")
    # any others needed?
    print()